/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projek.kelompok.apprentaldvd.view.component;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projek.kelompok.apprentaldvd.controlller.service.KoneksiFactory;
import projek.kelompok.apprentaldvd.controlller.service.ProdukDvdService;
import projek.kelompok.apprentaldvd.model.Dvd;
import projek.kelompok.apprentaldvd.view.ProdukDvd;

/**
 *
 * @author Feri Winarta
 */
public class DeleteDvd extends javax.swing.JFrame {    
    private ProdukDvdService service;
    private JFrame frame = this;
    
    public DeleteDvd(String idAdmin) {
        initComponents();
        
        // untuk menengahkan frame
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        service = new ProdukDvdService(new KoneksiFactory().getConn());
        tombolDeleteDiklik();
        tampilDataDvd();
        cekKode();
        
        
        JFrame frameIni = this;
        jButton3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                JFrame frame = new ProdukDvd(idAdmin);
                frameIni.setVisible(false);
                frame.setVisible(true);
            }
        });
        
    }
    
    public void tombolDeleteDiklik(){
        jButton1.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                
                try {
                    Dvd dvd = service.getSatuDvd(inputKode.getText());
                    int status = service.deleteDvd(dvd);
                    
                    if(status != 1) {
                        JOptionPane.showMessageDialog(frame, "Gagal menghapus dvd");
                    } else {
                        JOptionPane.showMessageDialog(frame, "Berhasil menghapus dvd");
                        inputKode.setText("");
                        labelJudul.setText("");
                        labelKategori.setText("");
                        labelQuantity.setText("");
                        labelharga.setText("");
                        tampilDataDvd();
                    }
                }catch(Exception ex) {
                    JOptionPane.showMessageDialog(frame, "Kode dvd belum diisi");
                }
                
            }             
        });
    }
    
    public void cekKode(){
        jButton2.addActionListener(new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent ae) {
                Dvd dvd = null;
  
                if(!inputKode.getText().isEmpty()) {
                    
                    try {
                        dvd = service.getSatuDvd(inputKode.getText());
                        labelJudul.setText(dvd.getJudulFilm());
                        labelKategori.setText(dvd.getKategori());
                        labelQuantity.setText(Integer.toString(dvd.getQuantity()));
                        BigDecimal bg = dvd.getHarga();
                        labelharga.setText(bg.toString());
                    }catch (Exception ex) {
                        JOptionPane.showMessageDialog(frame, "Kode tidak ditemukan");
                    }
                    
                } else {
                    JOptionPane.showMessageDialog(frame, "Kode tidak boleh kosong");
                }
                
            }
        }); 
    }
                
    
    public void tampilDataDvd() {
        DefaultTableModel dtf = (DefaultTableModel) jTable1.getModel();
        dtf.setRowCount(0);
        List<Dvd> semuaDvd = service.getSemuaDvd();
        
        for(Dvd value : semuaDvd) {
            Vector v2 = new Vector();
            v2.add(value.getKode());
            v2.add(value.getJudulFilm());
            v2.add(value.getKategori());
            v2.add(value.getQuantity());
            v2.add(value.getHarga());
            dtf.addRow(v2);
        }
    }
    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        harga = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        kategori = new javax.swing.JLabel();
        quantity = new javax.swing.JLabel();
        inputKode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        judul1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelharga = new javax.swing.JLabel();
        labelJudul = new javax.swing.JLabel();
        labelKategori = new javax.swing.JLabel();
        labelQuantity = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        harga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        harga.setText("Harga");
        jPanel1.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 100, 30));

        judul.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        judul.setText("Kode Dvd");
        jPanel1.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 100, 30));

        kategori.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kategori.setText("Kategori");
        jPanel1.add(kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 100, 30));

        quantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantity.setText("Quantity");
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, 30));
        jPanel1.add(inputKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 130, 30));

        jButton1.setText("DELETE");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 120, 70));

        judul1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        judul1.setText("Judul DVD");
        jPanel1.add(judul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 100, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Dvd", "Judul Dvd", "Kategori", "Quantity", "Harga"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 320, 310));
        jPanel1.add(labelharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 280, 30));
        jPanel1.add(labelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 280, 30));
        jPanel1.add(labelKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 280, 30));
        jPanel1.add(labelQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 280, 30));

        jButton2.setText("Cek Kode");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("DELETE DVD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 200, 30));

        jButton3.setText("Kembali");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteDvd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteDvd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteDvd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteDvd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel harga;
    private javax.swing.JTextField inputKode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel kategori;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelKategori;
    private javax.swing.JLabel labelQuantity;
    private javax.swing.JLabel labelharga;
    private javax.swing.JLabel quantity;
    // End of variables declaration//GEN-END:variables
}
